#!/usr/bin/env node
/**
 * Injects the current git commit hash into version.js and index.html so all
 * assets (including version.js and loader.js) get ?v=<hash> and refetch after deploy.
 * Called by .github/workflows/deploy.yml during deploy.
 */
const { execSync } = require('child_process');
const { readFileSync, writeFileSync } = require('fs');

const hash = execSync('git rev-parse --short HEAD').toString().trim();

/* ---- version.js ---- */
writeFileSync('version.js', `// Auto-generated by scripts/inject-version.cjs during deploy. Do not edit.\nvar CACHE_BUST = '${hash}';\n`);

/* ---- index.html: add ?v=hash to bootstrap script tags ---- */
let html = readFileSync('index.html', 'utf8');
html = html.replace(/src="(version\.js)(?:\?v=[^"]*)?"/, `src="$1?v=${hash}"`);
html = html.replace(/src="(loader\.js)(?:\?v=[^"]*)?"/, `src="$1?v=${hash}"`);
writeFileSync('index.html', html);

console.log('Injected CACHE_BUST:', hash);
