#!/usr/bin/env node
/**
 * Injects the current git commit hash into version.js, index.html, and manifest.json
 * so bootstrap assets, PWA manifest (and its icons), favicon + apple-touch links, and
 * Open Graph / Twitter preview image URLs refetch after deploy.
 * Called by .github/workflows/deploy.yml during deploy.
 */
const { execSync } = require('child_process');
const { readFileSync, writeFileSync } = require('fs');

const hash = execSync('git rev-parse --short HEAD').toString().trim();

/* ---- version.js ---- */
writeFileSync('version.js', `// Auto-generated by scripts/inject-version.cjs during deploy. Do not edit.\nvar CACHE_BUST = '${hash}';\n`);

/* ---- manifest.json: icon srcs need busting for PWA / install ---- */
let manifest = readFileSync('manifest.json', 'utf8');
manifest = manifest.replace(
  /"src": "app-icon\.png(?:\?v=[^"]*)?"/g,
  `"src": "app-icon.png?v=${hash}"`
);
writeFileSync('manifest.json', manifest);

/* ---- index.html: scripts, manifest, icons, link preview metas ---- */
let html = readFileSync('index.html', 'utf8');
html = html.replace(/src="(version\.js)(?:\?v=[^"]*)?"/, `src="$1?v=${hash}"`);
html = html.replace(/src="(loader\.js)(?:\?v=[^"]*)?"/, `src="$1?v=${hash}"`);
html = html.replace(/href="(manifest\.json)(?:\?v=[^"]*)?"/, `href="$1?v=${hash}"`);
html = html.replace(/href="(sprites\/juice-box\.png)(?:\?v=[^"]*)?"/, `href="$1?v=${hash}"`);
html = html.replace(/href="(app-icon\.png)(?:\?v=[^"]*)?"/g, `href="$1?v=${hash}"`);
html = html.replace(
  /content="(https:\/\/juiceboxgame\.com\/link-preview\.png)(?:\?v=[a-f0-9A-F]+)?"/gi,
  `content="$1?v=${hash}"`
);
writeFileSync('index.html', html);

console.log('Injected CACHE_BUST:', hash);
