#!/usr/bin/env node
/**
 * Overwrites version.js with the current git commit hash (short).
 * Called by .github/workflows/deploy.yml during deploy so CACHE_BUST
 * changes with each push; all assets get ?v=<hash> and refetch.
 */
const { execSync } = require('child_process');
const { writeFileSync } = require('fs');

const hash = execSync('git rev-parse --short HEAD').toString().trim();
const content = `// Auto-generated by scripts/inject-version.cjs during deploy. Do not edit.\nvar CACHE_BUST = '${hash}';\n`;

writeFileSync('version.js', content);
console.log('Injected CACHE_BUST:', hash);
